### ISSUE TITLE
Sass does not work

### ISSUE THREAD

**Issue by unpezllamadomiki** [wprig/wprig#124] opened 2018-09-20 21:22 UTC
Hello. This is my first time using wprig and I'm following the tutorial. I have several concern: the Sass part does not work. The conversion did not minimize the css. It is copied as it is and the browser does not show the changes.

I am using the software that you recomended (vs code and plugins) as well as ampps. My php version is 7.0. I will attach some screenshoots on this issue.

![image](https://user-images.githubusercontent.com/33034394/45847518-9a9ca280-bd2b-11e8-93c8-381a3a8b95ea.png)
![image](https://user-images.githubusercontent.com/33034394/45847582-c4ee6000-bd2b-11e8-8b0d-fd8cd152c68b.png)
![image](https://user-images.githubusercontent.com/33034394/45847623-e2232e80-bd2b-11e8-8b4e-9049108dcdb4.png)
![image](https://user-images.githubusercontent.com/33034394/45847644-f2d3a480-bd2b-11e8-8932-95e832689aa6.png)

**Comment by mor10** [comment] 2018-09-21 01:29
That's odd. I have to do some testing. Have you tried this with the v1.1 branch?

**Comment by mor10** [comment] 2018-10-02 00:53
I just tested an exact duplicate of the code you've posted here and it works as expected for me. The `.scss` files compile out correctly and I get the desired CSS in `main.css`. Have you tried setting up a fresh version of WPRig in a different folder to test if it's an issue with this particular install?

**Comment by mor10** [comment] 2018-10-02 00:56
Closing as I can't reproduce the issue. Feel free to reopen with more details.

**Closed by mor10** 2018-10-02 00:56 UTC
Labels: css, gulp

**Comment by ChrisBuck-Harness** [comment] 2021-01-24 05:29
Getting the same issue. I saw that in 2019 you wanted to remove Sass. Did you take it out of the gulp script?

If so, there's still a video up there saying that you can use sass, no problem (https://wprig.io/learn/sass-in-wp-rig/). But it's not compiling.
