### ISSUE TITLE
Mobile Nav sub menus default to being visible

### ISSUE THREAD

**Issue by mark60480** [wprig/wprig#660] opened 2020-09-18 21:46 UTC
## Issue Overview
This is a pretty quick, yes or no question about the way sub-menus are displayed on mobile screens in WP Rig by default. 
Anyone who uses WP Rig should be able to answer this. If I load an untouched version of WP Rig in a new, untouched Wordpress installation, add a couple sub-menu items, and view the site on a mobile screen - the sub-menu items default to being visible. Is this normal behavior, or is it just me? When I study the navigation.js, it seems to have scripting included that toggles the sub-menu items. Please let me know how the sub-menu items appear in your project in mobile view.

## Describe your environment
Mac with VS Code, viewing on mobile screen

## Steps to Reproduce

1. Download a fresh version of WP Rig
2. Install into fresh Wordpress site with sub-menu items in main nav
3. Check how menu looks on mobile screen
4. Are sub-menu items visible by default

## Expected Behavior
Expect sub-menu items to not be visible until a dropdown icon next to parent menu item is clicked.

## Current Behavior
Sub-menu items are alway visible on mobile screen view.

## Possible Solution
Could it be possible that the navigation.js is not being loaded?

## Screenshots / Video
![wp-rig_sub-menu-mobile](https://user-images.githubusercontent.com/23484360/93647648-8220fa80-f9ce-11ea-8e85-2d7561780e3f.jpg)

**Comment by alexwcoleman** [comment] 2020-09-25 19:17
this is normal behavior. closing this out.

**Closed by alexwcoleman** 2020-09-25 19:17 UTC

**Comment by mark60480** [comment] 2020-09-25 19:21
OK. Thanks for responding to this Alex.

**Comment by MahmoudHossameldin** [comment] 2020-12-16 18:14
I think this is a bug, if you look at the aria-label and aria-expanded attributes it seems like this wasn't the intended behavior.
Trying to solve it, would appreciate if anyone has solved it and could elaborate on the solution.
