### ISSUE TITLE
Enhancement: Support HTTPS

### ISSUE THREAD

**Issue by miklb** [wprig/wprig#6] opened 2018-06-14 22:08 UTC
## Issue Overview

Currently Browser sync only supports http
## Describe your environment

local dev environment running nginx via hombrew in macOS. Using a local SSL cert (not self-signed)
## Possible Solution

```
gulp.task('browser-sync', function() {
    browserSync.init({
        proxy: projectURL,
        https: {
            key: keyPath,
            cert: certPath
        }
    })
})
```
where `keyPath` and `certPath` are user variables for the respective paths. `projectURL` I believe is same as current `proxyURL` in the config. 

I'd guess a simple check for those variables from `themeConfig.js` and then passing them into the `https` key for `browserSync` should work.

Does that sound logical and if so, I can take a stab at a PR.

**Comment by miklb** [comment] 2018-06-14 23:40
Not quite that simple. Something in the watch function is failing, but the error message is unhelpful at this point. Will continue digging.

**Comment by miklb** [comment] 2018-06-15 00:09
As long as I don't pass the port with `https` I have it working.

**Comment by bamadesigner** [comment] 2018-08-15 19:52
This issue has been resolved and merged in v1.1 (which is under development and will be the next major release). To test this feature, you can check out the v1.1. branch. Thanks!

**Closed** 2018-08-15 20:06 UTC
Labels: enhancement

**Comment by hillal20** [comment] 2025-03-25 19:35
![Image](https://github.com/user-attachments/assets/6926abbf-6cbf-400e-97ca-a12fc782c9c2)

**Comment by hillal20** [comment] 2025-03-25 19:59
The problem is still existing until 2025
