### ISSUE TITLE
v2.0 Watch Error: Path.Replace is not a function

### ISSUE THREAD

**Issue by ehowey** [wprig/wprig#501] opened 2019-06-05 02:24 UTC
## Issue Overview
Using a fresh install of the v2.0 branch the watch process fails with this error:

20:17:52] Starting 'watch'...
[20:17:52] 'watch' errored after 2.32 ms
[20:17:52] TypeError: path.replace is not a function
    at replace (/Users/erichowey/Websites/lwbfinal/app/public/wp-content/themes/wprig-test/gulp/utils.js:122:14)
    at watch (/Users/erichowey/Websites/lwbfinal/app/public/wp-content/themes/wprig-test/gulp/watch.js:26:31)
    at bound (domain.js:395:14)
    at runBound (domain.js:408:12)
    at asyncRunner (/Users/erichowey/Websites/lwbfinal/app/public/wp-content/themes/wprig-test/node_modules/async-done/index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)
[20:17:52] 'default' errored after 51 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wprig@2.0.0 dev: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wprig@2.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/erichowey/.npm/_logs/2019-06-05T02_17_52_696Z-debug.log

## Describe your environment
MacOS 10.12
node v.10.15
npm v.6.4.1

Using LocalbyFlywheel if it matters

## Steps to Reproduce

1.  Download fresh copy of v2.0 branch
2.  npm run rig-init
3.  npm run dev
4.

## Expected Behavior
No error

## Possible Solution
I did some testing.  Removing #493 fixed this problem for me.

## Related Issues and/or PRs
This started happening for me when I merged in #429, #493, #495

**Comment by luminuu** [comment] 2019-06-05 18:57
I'm getting the same error, same setup and same steps to reproduce.

**Comment by ehowey** [comment] 2019-06-05 18:59
You can just remove the changes from PR #493 and that should fix it for you until they bug fix this.

**Comment by ehowey** [comment] 2019-06-05 19:46
@luminuu Can you test if your gulp watch process is working properly with styles?  Mine isn't now - it is not throwing any errors but it isn't actually rebuilding the files properly when I save a .css file, it is working properly with .php files.

**Comment by ehowey** [comment] 2019-06-06 16:05
It looks like this is fixed by #499

**Comment by ataylorme** [comment] 2019-06-06 16:08
Closing this as a duplicate of #498. #499 needs another review approval and then it will be merged. @ehowey in the meantime feel free to apply the changes there manually. Commenting on the PR as to whether it fixes things for you (or not) would be helpful.

**Closed by ataylorme** 2019-06-06 16:08 UTC
Labels: bug, gulp
